sm8450-common: parts: Fix ThermalSettingsFragment crash on null RecyclerView
ThermalSettingsFragment was not inflating the custom layout
(thermal_layout.xml), causing the default PreferenceFragment layout
to be used. As a result, thermal_rv_view was null and the app crashed
with a NullPointerException when setLayoutManager() was called.

Add onCreateView() to correctly inflate R.layout.thermal_layout.

Fixes:
java.lang.NullPointerException: Attempt to invoke virtual method
'void androidx.recyclerview.widget.RecyclerView.setLayoutManager(...)'
on a null object reference

Signed-off-by: dopaemon <polarisdp@gmail.com>